version: "3.7"

services:
  currency-service:
    build: "./currency-service" 
    ports:
      - 8081:8081

  product-service:
    build: "./product-service" 
    ports:
      - 8082:8082
    depends_on:
      - product-db
      - currency-service
    links:
      - product-db
      - currency-service      

  product-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - "./product-service/db/data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - product-db
    links:
      - product-db
