CREATE DATABASE products;

CREATE TABLE product
(
    id serial PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    currency char(3) DEFAULT 'BRL',
    price MONEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
